# ==================================================================
# MegaLinter - Auto
# ==================================================================
name: Lint Project Automatically

on:

    push:
        branches: [master]
    pull_request:

concurrency:
    group: ${{ github.ref }}-${{ github.workflow }}
    cancel-in-progress: true

jobs:

    call-megalinter:

        name: Call MegaLinter

        permissions:
            contents: read
            statuses: write
            packages: write

        uses: ragsworks/workflow-megalinter/.github/workflows/reusable-megalinter.yml@master
